---
aws:
  region: ap-southeast-2

stack_manager:
  ssm_stack_name: stack-manager-ssm
  stack_name: stack-manager-v2
  s3_bucket: aem-stack-builder
  s3_prefix: stack-manager
  version: v2

snapshots_purge:
  stack_name: aem-snapshots-purge
  UseGlobalDefaults: 'true'
  LiveSnapshotsPurgeSchedule: 'cron(10 20 1/3 * ? *)'
  OfflineSnapshotsPurgeSchedule: 'cron(15 19 ? * SUN *)'
  OrchestrationSnapshotsPurgeSchedule: 'cron(5 0/4 * * ? *)'
  LiveSnapshotsPurgeInput:  '"SnapshotType": "live", "Age": "1d"'
  OfflineSnapshotsPurgeInput:  '"SnapshotType": "offline", "Age": "1w"'
  OrchestrationSnapshotsPurgeInput: '"SnapshotType": "orchestration", "Age": "4h"'
